name: (Manual) Publish Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (e.g. 1.7.0-rc.1, 0.0.1-beta)'
        required: true
        default: 'snapshot'

jobs:
  manual-publish-docker-image:
    # There is currently no way to limit workflow dispatch to only allow default branch
    # so we need to restrict it here
    # See https://github.community/t/limit-branch-for-workflow-dispatch/122099
    if: github.ref == 'refs/heads/master' && github.repository == 'finos/legend-studio'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: finos/legend-studio
            package: '@finos/legend-application-studio-deployment'
          - image: finos/legend-query
            package: '@finos/legend-application-query-deployment'
          - image: local/legend-showcase-server
            package: '@finos/legend-server-showcase-deployment'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Setup Yarn cache
        uses: actions/cache@v4.1.0
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 21
      - name: Install dependencies
        run: yarn
      - name: Check Docker image tag
        run: node ./scripts/docker/checkDockerImageTag.js ${{ github.event.inputs.tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: finos
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to Docker
        run: yarn build && yarn workspace ${{ matrix.package }} publish:docker ${{ github.event.inputs.tag }}
        env:
          # Webpack build could consume a large amount of memory
          NODE_OPTIONS: '--max-old-space-size=4096'
